### ISSUE TITLE
[Feature] Update footer with club socials

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/pdf#7]
### Description

Update the footer with the correct links to our socials

Current:
![image](https://user-images.githubusercontent.com/24856195/194715994-4196a61f-506e-4eff-8d64-1d0222821eb5.png)

Replace these links with to our website, IG, Facebook, Medium, Slack, TartanConnect, and mailing list. You can find the links on the footer of our main [website](https://scottylabs.org/)

**Comment by justinzhang** [comment]
I can work on this
