### ISSUE TITLE
[Feature] Update branding assets with PDF

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/pdf#8]
### Description

Replace the brand icons and favicon with new assets for PDF once design releases them. Currently, old WDW assets are being used as placeholders

**Comment by gramliu** [comment]
![image](https://user-images.githubusercontent.com/24856195/195736675-bbd81115-abdf-4a1e-96e5-20d8f333868c.png)

**Comment by justinzhang** [comment]
Is there a png version of the logo?
